# Site settings
title: Directory of MSR Datasets
baseurl: "/directory-msr-datasets"
repository: AuthEceSoftEng/directory-msr-datasets

# Build settings
markdown: kramdown

# File settings
exclude: ["README.md", "LICENSE.md", "graphs.py", "Gemfile", "Gemfile.lock"]